// <auto-generated />
using ENSPRONET.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ENSPRONET.Services.Migrations
{
    [DbContext(typeof(ENSPRONETContext))]
    [Migration("20220208151329_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ENSPRONET.Domains.Domains.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetDomain")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumericCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubDivisionCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Alpha2Code = "KZ",
                            Alpha3Code = "KAZ",
                            CountryName = "Kazakhstan",
                            InternetDomain = ".kz",
                            NumericCode = 398,
                            SubDivisionCode = "KZ"
                        },
                        new
                        {
                            Id = 102,
                            Alpha2Code = "SM",
                            Alpha3Code = "SMR",
                            CountryName = "San Marino",
                            InternetDomain = ".sm",
                            NumericCode = 674,
                            SubDivisionCode = "SM"
                        },
                        new
                        {
                            Id = 103,
                            Alpha2Code = "GL",
                            Alpha3Code = "GRL",
                            CountryName = "Greenland",
                            InternetDomain = ".gl",
                            NumericCode = 304,
                            SubDivisionCode = "GL"
                        },
                        new
                        {
                            Id = 104,
                            Alpha2Code = "KH",
                            Alpha3Code = "KHM",
                            CountryName = "Cambodia",
                            InternetDomain = ".kh",
                            NumericCode = 116,
                            SubDivisionCode = "CB"
                        },
                        new
                        {
                            Id = 105,
                            Alpha2Code = "LB",
                            Alpha3Code = "LBN",
                            CountryName = "Lebanon",
                            InternetDomain = ".lb",
                            NumericCode = 422,
                            SubDivisionCode = "LE"
                        },
                        new
                        {
                            Id = 106,
                            Alpha2Code = "BG",
                            Alpha3Code = "BGR",
                            CountryName = "Bulgaria",
                            InternetDomain = ".bg",
                            NumericCode = 100,
                            SubDivisionCode = "BU"
                        },
                        new
                        {
                            Id = 107,
                            Alpha2Code = "CH",
                            Alpha3Code = "CHE",
                            CountryName = "Switzerland",
                            InternetDomain = ".ch",
                            NumericCode = 756,
                            SubDivisionCode = "SZ"
                        },
                        new
                        {
                            Id = 108,
                            Alpha2Code = "MX",
                            Alpha3Code = "MEX",
                            CountryName = "Mexico",
                            InternetDomain = ".mx",
                            NumericCode = 484,
                            SubDivisionCode = "MX"
                        },
                        new
                        {
                            Id = 109,
                            Alpha2Code = "GH",
                            Alpha3Code = "GHA",
                            CountryName = "Ghana",
                            InternetDomain = ".gh",
                            NumericCode = 288,
                            SubDivisionCode = "GH"
                        },
                        new
                        {
                            Id = 110,
                            Alpha2Code = "MA",
                            Alpha3Code = "MAR",
                            CountryName = "Morocco",
                            InternetDomain = ".ma",
                            NumericCode = 504,
                            SubDivisionCode = "MO"
                        },
                        new
                        {
                            Id = 111,
                            Alpha2Code = "CO",
                            Alpha3Code = "COL",
                            CountryName = "Colombia",
                            InternetDomain = ".co",
                            NumericCode = 170,
                            SubDivisionCode = "CO"
                        },
                        new
                        {
                            Id = 112,
                            Alpha2Code = "IQ",
                            Alpha3Code = "IRQ",
                            CountryName = "Iraq",
                            InternetDomain = ".iq",
                            NumericCode = 368,
                            SubDivisionCode = "IZ"
                        },
                        new
                        {
                            Id = 113,
                            Alpha2Code = "US",
                            Alpha3Code = "USA",
                            CountryName = "United States",
                            InternetDomain = ".us",
                            NumericCode = 840,
                            SubDivisionCode = "US"
                        },
                        new
                        {
                            Id = 114,
                            Alpha2Code = "NF",
                            Alpha3Code = "NFK",
                            CountryName = "Norfolk Island",
                            InternetDomain = ".nf",
                            NumericCode = 574,
                            SubDivisionCode = "NF"
                        },
                        new
                        {
                            Id = 115,
                            Alpha2Code = "UZ",
                            Alpha3Code = "UZB",
                            CountryName = "Uzbekistan",
                            InternetDomain = ".uz",
                            NumericCode = 860,
                            SubDivisionCode = "UZ"
                        },
                        new
                        {
                            Id = 116,
                            Alpha2Code = "MT",
                            Alpha3Code = "MLT",
                            CountryName = "Malta",
                            InternetDomain = ".mt",
                            NumericCode = 470,
                            SubDivisionCode = "MT"
                        },
                        new
                        {
                            Id = 117,
                            Alpha2Code = "NP",
                            Alpha3Code = "NPL",
                            CountryName = "Nepal",
                            InternetDomain = ".np",
                            NumericCode = 524,
                            SubDivisionCode = "NP"
                        },
                        new
                        {
                            Id = 118,
                            Alpha2Code = "NG",
                            Alpha3Code = "NGA",
                            CountryName = "Nigeria",
                            InternetDomain = ".ng",
                            NumericCode = 566,
                            SubDivisionCode = "NI"
                        },
                        new
                        {
                            Id = 119,
                            Alpha2Code = "AO",
                            Alpha3Code = "AGO",
                            CountryName = "Angola",
                            InternetDomain = ".ao",
                            NumericCode = 24,
                            SubDivisionCode = "AO"
                        },
                        new
                        {
                            Id = 120,
                            Alpha2Code = "AM",
                            Alpha3Code = "ARM",
                            CountryName = "Armenia",
                            InternetDomain = ".am",
                            NumericCode = 51,
                            SubDivisionCode = "AM"
                        },
                        new
                        {
                            Id = 121,
                            Alpha2Code = "CY",
                            Alpha3Code = "CYP",
                            CountryName = "Cyprus",
                            InternetDomain = ".cy",
                            NumericCode = 196,
                            SubDivisionCode = "CY"
                        },
                        new
                        {
                            Id = 122,
                            Alpha2Code = "CD",
                            Alpha3Code = "COD",
                            CountryName = "Democratic Republic of the Congo",
                            InternetDomain = ".cd",
                            NumericCode = 180,
                            SubDivisionCode = "CG"
                        },
                        new
                        {
                            Id = 123,
                            Alpha2Code = "ET",
                            Alpha3Code = "ETH",
                            CountryName = "Ethiopia",
                            InternetDomain = ".et",
                            NumericCode = 231,
                            SubDivisionCode = "ET"
                        },
                        new
                        {
                            Id = 124,
                            Alpha2Code = "MA",
                            Alpha3Code = "MAR",
                            CountryName = "Morocco",
                            InternetDomain = ".ma",
                            NumericCode = 504,
                            SubDivisionCode = "MO"
                        },
                        new
                        {
                            Id = 125,
                            Alpha2Code = "TF",
                            Alpha3Code = "ATF",
                            CountryName = "French Southern Territories",
                            InternetDomain = ".tf",
                            NumericCode = 260,
                            SubDivisionCode = "FS"
                        },
                        new
                        {
                            Id = 126,
                            Alpha2Code = "BW",
                            Alpha3Code = "BWA",
                            CountryName = "Botswana",
                            InternetDomain = ".bw",
                            NumericCode = 72,
                            SubDivisionCode = "BC"
                        },
                        new
                        {
                            Id = 127,
                            Alpha2Code = "SC",
                            Alpha3Code = "SYC",
                            CountryName = "Seychelles",
                            InternetDomain = ".sc",
                            NumericCode = 690,
                            SubDivisionCode = "SE"
                        },
                        new
                        {
                            Id = 128,
                            Alpha2Code = "SE",
                            Alpha3Code = "SWE",
                            CountryName = "Sweden",
                            InternetDomain = ".se",
                            NumericCode = 752,
                            SubDivisionCode = "SW"
                        },
                        new
                        {
                            Id = 129,
                            Alpha2Code = "JE",
                            Alpha3Code = "JEY",
                            CountryName = "Jersey",
                            InternetDomain = ".je",
                            NumericCode = 832,
                            SubDivisionCode = "JE"
                        },
                        new
                        {
                            Id = 130,
                            Alpha2Code = "TM",
                            Alpha3Code = "TKM",
                            CountryName = "Turkmenistan",
                            InternetDomain = ".tm",
                            NumericCode = 795,
                            SubDivisionCode = "TX"
                        },
                        new
                        {
                            Id = 131,
                            Alpha2Code = "HT",
                            Alpha3Code = "HTI",
                            CountryName = "Haiti",
                            InternetDomain = ".ht",
                            NumericCode = 332,
                            SubDivisionCode = "HA"
                        },
                        new
                        {
                            Id = 132,
                            Alpha2Code = "BT",
                            Alpha3Code = "BTN",
                            CountryName = "Bhutan",
                            InternetDomain = ".bt",
                            NumericCode = 64,
                            SubDivisionCode = "BT"
                        },
                        new
                        {
                            Id = 133,
                            Alpha2Code = "CM",
                            Alpha3Code = "CMR",
                            CountryName = "Cameroon",
                            InternetDomain = ".cm",
                            NumericCode = 120,
                            SubDivisionCode = "CM"
                        },
                        new
                        {
                            Id = 134,
                            Alpha2Code = "AW",
                            Alpha3Code = "ABW",
                            CountryName = "Aruba",
                            InternetDomain = ".aw",
                            NumericCode = 533,
                            SubDivisionCode = "AA"
                        },
                        new
                        {
                            Id = 135,
                            Alpha2Code = "AX",
                            Alpha3Code = "ALA",
                            CountryName = "Aland Islands",
                            InternetDomain = ".ax",
                            NumericCode = 248,
                            SubDivisionCode = ""
                        },
                        new
                        {
                            Id = 136,
                            Alpha2Code = "EC",
                            Alpha3Code = "ECU",
                            CountryName = "Ecuador",
                            InternetDomain = ".ec",
                            NumericCode = 218,
                            SubDivisionCode = "EC"
                        },
                        new
                        {
                            Id = 137,
                            Alpha2Code = "GG",
                            Alpha3Code = "GGY",
                            CountryName = "Guernsey",
                            InternetDomain = ".gg",
                            NumericCode = 831,
                            SubDivisionCode = "GK"
                        },
                        new
                        {
                            Id = 138,
                            Alpha2Code = "TD",
                            Alpha3Code = "TCD",
                            CountryName = "Chad",
                            InternetDomain = ".td",
                            NumericCode = 148,
                            SubDivisionCode = "CD"
                        },
                        new
                        {
                            Id = 139,
                            Alpha2Code = "GN",
                            Alpha3Code = "GIN",
                            CountryName = "Guinea",
                            InternetDomain = ".gn",
                            NumericCode = 324,
                            SubDivisionCode = "GV"
                        },
                        new
                        {
                            Id = 140,
                            Alpha2Code = "GA",
                            Alpha3Code = "GAB",
                            CountryName = "Gabon",
                            InternetDomain = ".ga",
                            NumericCode = 266,
                            SubDivisionCode = "GB"
                        },
                        new
                        {
                            Id = 141,
                            Alpha2Code = "FM",
                            Alpha3Code = "FSM",
                            CountryName = "Micronesia",
                            InternetDomain = ".fm",
                            NumericCode = 583,
                            SubDivisionCode = "FM"
                        },
                        new
                        {
                            Id = 142,
                            Alpha2Code = "AL",
                            Alpha3Code = "ALB",
                            CountryName = "Albania",
                            InternetDomain = ".al",
                            NumericCode = 8,
                            SubDivisionCode = "AL"
                        },
                        new
                        {
                            Id = 143,
                            Alpha2Code = "LT",
                            Alpha3Code = "LTU",
                            CountryName = "Lithuania",
                            InternetDomain = ".lt",
                            NumericCode = 440,
                            SubDivisionCode = "LH"
                        },
                        new
                        {
                            Id = 144,
                            Alpha2Code = "MN",
                            Alpha3Code = "MNG",
                            CountryName = "Mongolia",
                            InternetDomain = ".mn",
                            NumericCode = 496,
                            SubDivisionCode = "MG"
                        },
                        new
                        {
                            Id = 145,
                            Alpha2Code = "BH",
                            Alpha3Code = "BHR",
                            CountryName = "Bahrain",
                            InternetDomain = ".bh",
                            NumericCode = 48,
                            SubDivisionCode = "BA"
                        },
                        new
                        {
                            Id = 146,
                            Alpha2Code = "CC",
                            Alpha3Code = "CCK",
                            CountryName = "Cocos Islands",
                            InternetDomain = ".cc",
                            NumericCode = 166,
                            SubDivisionCode = "CK"
                        },
                        new
                        {
                            Id = 147,
                            Alpha2Code = "MS",
                            Alpha3Code = "MSR",
                            CountryName = "Montserrat",
                            InternetDomain = ".ms",
                            NumericCode = 500,
                            SubDivisionCode = "MH"
                        },
                        new
                        {
                            Id = 148,
                            Alpha2Code = "BO",
                            Alpha3Code = "BOL",
                            CountryName = "Bolivia",
                            InternetDomain = ".bo",
                            NumericCode = 68,
                            SubDivisionCode = "BL"
                        },
                        new
                        {
                            Id = 149,
                            Alpha2Code = "GM",
                            Alpha3Code = "GMB",
                            CountryName = "Gambia",
                            InternetDomain = ".gm",
                            NumericCode = 270,
                            SubDivisionCode = "GA"
                        },
                        new
                        {
                            Id = 150,
                            Alpha2Code = "CV",
                            Alpha3Code = "CPV",
                            CountryName = "Cabo Verde",
                            InternetDomain = ".cv",
                            NumericCode = 132,
                            SubDivisionCode = "CV"
                        },
                        new
                        {
                            Id = 151,
                            Alpha2Code = "FO",
                            Alpha3Code = "FRO",
                            CountryName = "Faroe Islands",
                            InternetDomain = ".fo",
                            NumericCode = 234,
                            SubDivisionCode = "FO"
                        },
                        new
                        {
                            Id = 152,
                            Alpha2Code = "MP",
                            Alpha3Code = "MNP",
                            CountryName = "Northern Mariana Islands",
                            InternetDomain = ".mp",
                            NumericCode = 580,
                            SubDivisionCode = "CQ"
                        },
                        new
                        {
                            Id = 153,
                            Alpha2Code = "LV",
                            Alpha3Code = "LVA",
                            CountryName = "Latvia",
                            InternetDomain = ".lv",
                            NumericCode = 428,
                            SubDivisionCode = "LG"
                        },
                        new
                        {
                            Id = 154,
                            Alpha2Code = "SZ",
                            Alpha3Code = "SWZ",
                            CountryName = "Eswatini",
                            InternetDomain = ".sz",
                            NumericCode = 748,
                            SubDivisionCode = "WZ"
                        },
                        new
                        {
                            Id = 155,
                            Alpha2Code = "GM",
                            Alpha3Code = "GMB",
                            CountryName = "Gambia",
                            InternetDomain = ".gm",
                            NumericCode = 270,
                            SubDivisionCode = "GA"
                        },
                        new
                        {
                            Id = 156,
                            Alpha2Code = "JM",
                            Alpha3Code = "JAM",
                            CountryName = "Jamaica",
                            InternetDomain = ".jm",
                            NumericCode = 388,
                            SubDivisionCode = "JM"
                        },
                        new
                        {
                            Id = 157,
                            Alpha2Code = "TF",
                            Alpha3Code = "ATF",
                            CountryName = "French Southern Territories",
                            InternetDomain = ".tf",
                            NumericCode = 260,
                            SubDivisionCode = "FS"
                        },
                        new
                        {
                            Id = 158,
                            Alpha2Code = "BS",
                            Alpha3Code = "BHS",
                            CountryName = "Bahamas",
                            InternetDomain = ".bs",
                            NumericCode = 44,
                            SubDivisionCode = "BF"
                        },
                        new
                        {
                            Id = 159,
                            Alpha2Code = "PW",
                            Alpha3Code = "PLW",
                            CountryName = "Palau",
                            InternetDomain = ".pw",
                            NumericCode = 585,
                            SubDivisionCode = "PS"
                        },
                        new
                        {
                            Id = 160,
                            Alpha2Code = "LT",
                            Alpha3Code = "LTU",
                            CountryName = "Lithuania",
                            InternetDomain = ".lt",
                            NumericCode = 440,
                            SubDivisionCode = "LH"
                        },
                        new
                        {
                            Id = 161,
                            Alpha2Code = "BO",
                            Alpha3Code = "BOL",
                            CountryName = "Bolivia",
                            InternetDomain = ".bo",
                            NumericCode = 68,
                            SubDivisionCode = "BL"
                        },
                        new
                        {
                            Id = 162,
                            Alpha2Code = "DZ",
                            Alpha3Code = "DZA",
                            CountryName = "Algeria",
                            InternetDomain = ".dz",
                            NumericCode = 12,
                            SubDivisionCode = "AG"
                        },
                        new
                        {
                            Id = 163,
                            Alpha2Code = "ES",
                            Alpha3Code = "ESP",
                            CountryName = "Spain",
                            InternetDomain = ".es",
                            NumericCode = 724,
                            SubDivisionCode = "SP"
                        },
                        new
                        {
                            Id = 164,
                            Alpha2Code = "BI",
                            Alpha3Code = "BDI",
                            CountryName = "Burundi",
                            InternetDomain = ".bi",
                            NumericCode = 108,
                            SubDivisionCode = "BY"
                        },
                        new
                        {
                            Id = 165,
                            Alpha2Code = "TD",
                            Alpha3Code = "TCD",
                            CountryName = "Chad",
                            InternetDomain = ".td",
                            NumericCode = 148,
                            SubDivisionCode = "CD"
                        },
                        new
                        {
                            Id = 166,
                            Alpha2Code = "AN",
                            Alpha3Code = "ANT",
                            CountryName = "Netherlands Antilles",
                            InternetDomain = ".an",
                            NumericCode = 530,
                            SubDivisionCode = "NT"
                        },
                        new
                        {
                            Id = 167,
                            Alpha2Code = "KN",
                            Alpha3Code = "KNA",
                            CountryName = "Saint Kitts and Nevis",
                            InternetDomain = ".kn",
                            NumericCode = 659,
                            SubDivisionCode = "SC"
                        },
                        new
                        {
                            Id = 168,
                            Alpha2Code = "MS",
                            Alpha3Code = "MSR",
                            CountryName = "Montserrat",
                            InternetDomain = ".ms",
                            NumericCode = 500,
                            SubDivisionCode = "MH"
                        },
                        new
                        {
                            Id = 169,
                            Alpha2Code = "YE",
                            Alpha3Code = "YEM",
                            CountryName = "Yemen",
                            InternetDomain = ".ye",
                            NumericCode = 887,
                            SubDivisionCode = "YM"
                        },
                        new
                        {
                            Id = 170,
                            Alpha2Code = "KE",
                            Alpha3Code = "KEN",
                            CountryName = "Kenya",
                            InternetDomain = ".ke",
                            NumericCode = 404,
                            SubDivisionCode = "KE"
                        },
                        new
                        {
                            Id = 171,
                            Alpha2Code = "CO",
                            Alpha3Code = "COL",
                            CountryName = "Colombia",
                            InternetDomain = ".co",
                            NumericCode = 170,
                            SubDivisionCode = "CO"
                        },
                        new
                        {
                            Id = 172,
                            Alpha2Code = "BO",
                            Alpha3Code = "BOL",
                            CountryName = "Bolivia",
                            InternetDomain = ".bo",
                            NumericCode = 68,
                            SubDivisionCode = "BL"
                        },
                        new
                        {
                            Id = 173,
                            Alpha2Code = "MS",
                            Alpha3Code = "MSR",
                            CountryName = "Montserrat",
                            InternetDomain = ".ms",
                            NumericCode = 500,
                            SubDivisionCode = "MH"
                        },
                        new
                        {
                            Id = 174,
                            Alpha2Code = "IR",
                            Alpha3Code = "IRN",
                            CountryName = "Iran",
                            InternetDomain = ".ir",
                            NumericCode = 364,
                            SubDivisionCode = "IR"
                        },
                        new
                        {
                            Id = 175,
                            Alpha2Code = "MM",
                            Alpha3Code = "MMR",
                            CountryName = "Myanmar",
                            InternetDomain = ".mm",
                            NumericCode = 104,
                            SubDivisionCode = "BM"
                        },
                        new
                        {
                            Id = 176,
                            Alpha2Code = "PY",
                            Alpha3Code = "PRY",
                            CountryName = "Paraguay",
                            InternetDomain = ".py",
                            NumericCode = 600,
                            SubDivisionCode = "PA"
                        },
                        new
                        {
                            Id = 177,
                            Alpha2Code = "UZ",
                            Alpha3Code = "UZB",
                            CountryName = "Uzbekistan",
                            InternetDomain = ".uz",
                            NumericCode = 860,
                            SubDivisionCode = "UZ"
                        },
                        new
                        {
                            Id = 178,
                            Alpha2Code = "TK",
                            Alpha3Code = "TKL",
                            CountryName = "Tokelau",
                            InternetDomain = ".tk",
                            NumericCode = 772,
                            SubDivisionCode = "TL"
                        },
                        new
                        {
                            Id = 179,
                            Alpha2Code = "PL",
                            Alpha3Code = "POL",
                            CountryName = "Poland",
                            InternetDomain = ".pl",
                            NumericCode = 616,
                            SubDivisionCode = "PL"
                        },
                        new
                        {
                            Id = 180,
                            Alpha2Code = "AU",
                            Alpha3Code = "AUS",
                            CountryName = "Australia",
                            InternetDomain = ".au",
                            NumericCode = 36,
                            SubDivisionCode = "AS"
                        },
                        new
                        {
                            Id = 181,
                            Alpha2Code = "GG",
                            Alpha3Code = "GGY",
                            CountryName = "Guernsey",
                            InternetDomain = ".gg",
                            NumericCode = 831,
                            SubDivisionCode = "GK"
                        },
                        new
                        {
                            Id = 182,
                            Alpha2Code = "VI",
                            Alpha3Code = "VIR",
                            CountryName = "U.S. Virgin Islands",
                            InternetDomain = ".vi",
                            NumericCode = 850,
                            SubDivisionCode = "VQ"
                        },
                        new
                        {
                            Id = 183,
                            Alpha2Code = "GL",
                            Alpha3Code = "GRL",
                            CountryName = "Greenland",
                            InternetDomain = ".gl",
                            NumericCode = 304,
                            SubDivisionCode = "GL"
                        },
                        new
                        {
                            Id = 184,
                            Alpha2Code = "PF",
                            Alpha3Code = "PYF",
                            CountryName = "French Polynesia",
                            InternetDomain = ".pf",
                            NumericCode = 258,
                            SubDivisionCode = "FP"
                        },
                        new
                        {
                            Id = 185,
                            Alpha2Code = "NA",
                            Alpha3Code = "NAM",
                            CountryName = "Namibia",
                            InternetDomain = ".na",
                            NumericCode = 516,
                            SubDivisionCode = "WA"
                        },
                        new
                        {
                            Id = 186,
                            Alpha2Code = "SC",
                            Alpha3Code = "SYC",
                            CountryName = "Seychelles",
                            InternetDomain = ".sc",
                            NumericCode = 690,
                            SubDivisionCode = "SE"
                        },
                        new
                        {
                            Id = 187,
                            Alpha2Code = "TR",
                            Alpha3Code = "TUR",
                            CountryName = "Turkey",
                            InternetDomain = ".tr",
                            NumericCode = 792,
                            SubDivisionCode = "TU"
                        },
                        new
                        {
                            Id = 188,
                            Alpha2Code = "BV",
                            Alpha3Code = "BVT",
                            CountryName = "Bouvet Island",
                            InternetDomain = ".bv",
                            NumericCode = 74,
                            SubDivisionCode = "BV"
                        },
                        new
                        {
                            Id = 189,
                            Alpha2Code = "TO",
                            Alpha3Code = "TON",
                            CountryName = "Tonga",
                            InternetDomain = ".to",
                            NumericCode = 776,
                            SubDivisionCode = "TN"
                        },
                        new
                        {
                            Id = 190,
                            Alpha2Code = "KR",
                            Alpha3Code = "KOR",
                            CountryName = "South Korea",
                            InternetDomain = ".kr",
                            NumericCode = 410,
                            SubDivisionCode = "KS"
                        },
                        new
                        {
                            Id = 191,
                            Alpha2Code = "HT",
                            Alpha3Code = "HTI",
                            CountryName = "Haiti",
                            InternetDomain = ".ht",
                            NumericCode = 332,
                            SubDivisionCode = "HA"
                        },
                        new
                        {
                            Id = 192,
                            Alpha2Code = "GH",
                            Alpha3Code = "GHA",
                            CountryName = "Ghana",
                            InternetDomain = ".gh",
                            NumericCode = 288,
                            SubDivisionCode = "GH"
                        },
                        new
                        {
                            Id = 193,
                            Alpha2Code = "GG",
                            Alpha3Code = "GGY",
                            CountryName = "Guernsey",
                            InternetDomain = ".gg",
                            NumericCode = 831,
                            SubDivisionCode = "GK"
                        },
                        new
                        {
                            Id = 194,
                            Alpha2Code = "CD",
                            Alpha3Code = "COD",
                            CountryName = "Democratic Republic of the Congo",
                            InternetDomain = ".cd",
                            NumericCode = 180,
                            SubDivisionCode = "CG"
                        },
                        new
                        {
                            Id = 195,
                            Alpha2Code = "JO",
                            Alpha3Code = "JOR",
                            CountryName = "Jordan",
                            InternetDomain = ".jo",
                            NumericCode = 400,
                            SubDivisionCode = "JO"
                        },
                        new
                        {
                            Id = 196,
                            Alpha2Code = "CG",
                            Alpha3Code = "COG",
                            CountryName = "Republic of the Congo",
                            InternetDomain = ".cg",
                            NumericCode = 178,
                            SubDivisionCode = "CF"
                        },
                        new
                        {
                            Id = 197,
                            Alpha2Code = "LK",
                            Alpha3Code = "LKA",
                            CountryName = "Sri Lanka",
                            InternetDomain = ".lk",
                            NumericCode = 144,
                            SubDivisionCode = "CE"
                        },
                        new
                        {
                            Id = 198,
                            Alpha2Code = "VE",
                            Alpha3Code = "VEN",
                            CountryName = "Venezuela",
                            InternetDomain = ".ve",
                            NumericCode = 862,
                            SubDivisionCode = "VE"
                        },
                        new
                        {
                            Id = 199,
                            Alpha2Code = "MT",
                            Alpha3Code = "MLT",
                            CountryName = "Malta",
                            InternetDomain = ".mt",
                            NumericCode = 470,
                            SubDivisionCode = "MT"
                        },
                        new
                        {
                            Id = 200,
                            Alpha2Code = "CZ",
                            Alpha3Code = "CZE",
                            CountryName = "Czechia",
                            InternetDomain = ".cz",
                            NumericCode = 203,
                            SubDivisionCode = "EZ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
